### ISSUE TITLE
Picking points for alignment

### ISSUE THREAD

**Issue by Anna486** [patmo141/object_alignment#22]
Hello
I've got a problem when I try to pick points for aligment.
When I select both the base object an the align object and click on "Align: Picked Points" Button I get this error:

Traceback (most recent call last):
  File "/home/anna/.config/blender/2.80/scripts/addons/object_alignment-b_280/operators/align_pick_points.py", line 320, in invoke
    bpy.ops.screen.region_toggle(ctx, region_type='UI')
  File "/home/anna/Pulpit/blender 2.8/blender-2.80-linux-glibc217-x86_64/2.80/scripts/modules/bpy/ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.screen.region_toggle" error, could not be found

location: <unknown location>:-1
Alignment version 0.2.0, branch 2.80

**Comment by patmo141** [comment]
Hi Anna,

Can you confirm which versions of blender you are using with each of these.  Also let's split this up into two issues (b_280 branch and 2.79 branch).  Please post info from splash screen on your blender version.  Thanks!

**Comment by patmo141** [comment]
For the blender 2.8x error, region_toggle definitely exists.  I think this may be an API blender version issue.

https://docs.blender.org/api/current/bpy.ops.screen.html?highlight=region_toggle#bpy.ops.screen.region_toggle

**Comment by patmo141** [comment]
However in version 2.80 of Blender, region_toggle was not in the API yet.  https://docs.blender.org/api/2.80/bpy.ops.screen.html?highlight=bpy%20ops%20screen#module-bpy.ops.screen

Can you test out with Blender 2.81 or 2.82.  I just put this update in to keep up with the current version of blender API.

**Comment by Anna486** [comment]
Hi Patmo,
 Following your suggestion I've installed Blender 2.82a and the addon works.
This is splash screen of 2.80. I used version b_280 branch. Interesting, now I see that I lose base object after clicking "Align:Picked Points"

![Zrzut ekranu z 2020-03-25 21-06-38](https://user-images.githubusercontent.com/62502457/77580675-b4004b00-6edc-11ea-9b53-aa963dc38466.png)
![Zrzut ekranu z 2020-03-25 21-25-00](https://user-images.githubusercontent.com/62502457/77582339-84067700-6edf-11ea-8af8-0d8040c85abe.png)
![Zrzut ekranu z 2020-03-25 21-16-38](https://user-images.githubusercontent.com/62502457/77581540-2b82aa00-6ede-11ea-9ca2-ed8c7cdfae80.png)
![Zrzut ekranu z 2020-03-25 21-17-34](https://user-images.githubusercontent.com/62502457/77581579-3dfce380-6ede-11ea-95a3-16115286d23c.png)

 I'm curious if I do somethig wrong? Anyway, thanks for your answer!
 Regards, Anna

**Comment by darkfibre-nl** [comment]
Hello Patrick!

Here's an additional 'bug' report.
I've tried using this add-on on the following versions of blender 2.8x:

(v2.81a) - 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: `rBf1aa4d18d49d`
(v2.82a) - 2.82 (sub 7), branch: master, commit date: 2020-03-12 05:06, hash: `rB375c7dc4caf4`
(v2.83 alpha) - 2.83 (sub 11), branch: master, commit date: 2020-03-24 23:23, hash: `rB188ccfb0dd67`

All return an error when clicking Align: Picked points, so I haven't been able to use it.
Is this an user error, or is something amiss in the add-on?

I can't seem to find documentation to help me along, some instructions, however brief, would be greatly appreciated.

v2.81a
![image](https://user-images.githubusercontent.com/8095682/77743174-f24e5500-7017-11ea-9600-27aaf15c9c81.png)

v2.82a
![image](https://user-images.githubusercontent.com/8095682/77743082-d34fc300-7017-11ea-9c2e-3e8cbcd1c193.png)

v2.83 alpha
![image](https://user-images.githubusercontent.com/8095682/77742996-ad2a2300-7017-11ea-863a-06b5973bbe15.png)

**Comment by patmo141** [comment]
You are using the wrong branch of the add-on!  Make sure you download the
b_280 branch

**Comment by darkfibre-nl** [comment]
Thanks! Works now!...

(btw: do you accept (new)issues here for feature requests?)

**Comment by patmo141** [comment]
Yes just start a new issue

**Comment by CADMAN1** [comment]
Hi Patrick, I can't get the tool to work on any of the versions you have recommended. It always gives me an error. What could I do to fix it?
![Object aligtment](https://user-images.githubusercontent.com/50122158/98451750-0bd88300-2149-11eb-81b0-eb6ec7955923.png)
