### ISSUE TITLE
mouse_x unrecognized, blender 2.7

### ISSUE THREAD

**Issue by patmo141** [patmo141/object_alignment#23]
Blender 2.79 on different laptop there is another problem:

Traceback (most recent call last):
  File "/home/akmint19/.config/blender/2.79/scripts/addons/object_alignment-master/operators/align_pick_points.py", line 267, in invoke
    bpy.ops.screen.area_split(override, direction='VERTICAL', factor=0.5, mouse_x=-100, mouse_y=-100)
  File "/home/akmint19/Pulpit/blender-2.79-e045fe53f1b0-linux-glibc217-x86_64/2.79/scripts/modules/bpy/ops.py", line 195, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties: : keyword "mouse_x" unrecognized

location: <unknown location>:-1

**Comment by Anna486** [comment]
Version with error message:
![blender xxxxxxxxx](https://user-images.githubusercontent.com/62502457/77585186-5e2fa100-6ee4-11ea-83ed-0d205811b894.png)

Version without error message:
![Zrzut ekranu z 2020-03-25 20-34-33](https://user-images.githubusercontent.com/62502457/77585406-bd8db100-6ee4-11ea-9253-eea44e48726c.png)
